.gitignore
README.md

Added readme template with basic project details

v1 of Readme

---

package-lock.json
package.json
views/dashboard.ejs
views/partials/header.ejs

- Add nodemon
- Change project name in header partial, package.json
- dashboard.ejs skeleton

Add nodemon, dashboard skeleton

---

public/main.js
public/style.css
views/dashboard.ejs

- Added main.js with rough switch statement to change div color
- add grid display for this week
- commented out EJS to get page to display

Set up weekly mood display

---

views/checkin.ejs

Add form with date picker, drop down menu, note section with 140 characters limit and submit button.

Add checkin

---

controllers/dashboard.js

updated getDashboard controller

---

public/main.js
views/dashboard.ejs

Added username to dashboard greeting; pulls username from DB.

User greeting added

---

routes/checkin.js
views/checkin.ejs

I know we want to change this to a put request later if we can automatically create a document for each checkin each day, but for now we should have a working put request to create some test data to put into the dashboard.

added post route for checkin

---

public/main.js
views/dashboard.ejs

Print empty mood boxes
- change divs to ul/li for moods
- add for loop to print empty mood history boxes
Mood boxes pull values from checkin
- current-week boxes pull values from checkin by index (i) via for loop

Print empty mood boxes

---

views/checkin.ejs

Edited the checkin.ejs file so that the form data submits correctly.

Issue # 27 / Checkin EJS template needs work

---

public/style.css
views/dashboard.ejs

dashboard styling

---

controllers/dashboard.js
views/dashboard.ejs

sorted date by descending order so that your most recent entry shows up first

added sort to dashboard controller

---

public/style.css
tailwind.config.js
views/dashboard.ejs
views/partials/footer.ejs
views/partials/header.ejs

more styling

---

views/dashboard.ejs

Dashboard ejs now renders a div for each square, renders all checkins first, then renders 70 - checkins if there are less than 70 checkins

changed ejs to render divs for the boxes

---

views/checkin.ejs

https://github.com/HattieTavares/mood-colors/issues/35

#35/Add a back or cancel button to the checkin page

---

views/dashboard.ejs

Dashboard.ejs now renders squares with color according to check in data.

added colors to render

---

public/style.css
views/dashboard.ejs

dashboard style changes

---

views/dashboard.ejs

accidentally deleted sizing in conflict, fixed

refix sizes

---

public/style.css
views/checkin.ejs

- Add style to checkin page to match Figma design
- Adjust public > style.css to add missing tailwind styles

#43 Add styling to checkin page 

---

controllers/dashboard.js
public/style.css
src/style.css
tailwind.config.js
views/checkin.ejs
views/dashboard.ejs
views/partials/footer.ejs
views/partials/header.ejs

made text sizes change for responsiveness, took cancel button out of form on checkin page

footer text fixed

---

views/index.ejs

updated tailwind styling on the index page. has borders now and proper spacing.

updated index styling

---

public/style.css

added the button animation in style.css file

added button animation

---

public/style.css
src/style.css
views/checkin.ejs

checkin page style

---

public/style.css
src/style.css
views/dashboard.ejs

key to count days for each mood, and put the button animations in with tailwind styling so they wouldn't get overwritten!

added key to dashboard page and re-added button styling that got removed

---

models/Checkin.js

Added unique-true property to Checkin model

---

public/style.css
views/dashboard.ejs

Reverts HattieTavares/mood-colors#66

Revert "Center dashboard pop ups and add border to squares on hover"

---

README.md

#64 Add all contributors info/socials to the README.md

---

README.md

Add gif of working demo for project to README.md

Add gif of working demo for project to README.md

---

public/style.css
src/style.css
views/checkin.ejs
views/dashboard.ejs
views/index.ejs
views/login.ejs
views/signup.ejs

Changed all non form buttons to just a href links and applied the same styling they had previously. Added a bit of margin to the error messages showing up too close to the boxes on login/sign up forms

fixed buttons

---

controllers/checkin.js
controllers/dashboard.js
views/checkin.ejs

Added code to the controller to check if the date existed before posting a new document. Fixes issue #50

fixed the bug where users could check in more than once per day
